### ISSUE TITLE
Is there any reason than Foundatio.RabbitMQ do not support Queue Plugin?

### ISSUE THREAD

**Issue by sampsonye** [FoundatioFx/Foundatio.RabbitMQ#31]
Is there any reason than Foundatio.RabbitMQ do not support Queue Plugin?

**Comment by niemyjski** [comment]
We mainly see it as a message bus and had no requirements at the time to use it as a queue. We use it in our apps for a message bus and then user azure storage queues or SQS for queues. Would you like to add support for this?

**Comment by sampsonye** [comment]
ok I will try to do this

**Comment by niemyjski** [comment]
We'd be willing to accept a pr for a queue implementation. I'm going to close this issue, but feel free to reference it in a pr!
